### ISSUE TITLE
🐛 [BUG] - Unable to add a List (Advanced Block)

### ISSUE THREAD

**Issue by yassine-sallemi** [Hexastack/Hexabot#22]
### Description

Adding a List block fails.
Console logs show a 400 Bad Request error with the message: 'Message is invalid'
![Capture d'écran 2024-09-16 144736](https://github.com/user-attachments/assets/889f5cd6-64f0-48e1-89e6-f9bb15ab6186)

### Reproduction steps

```bash
1. Go to 'Visual Editor'
2. Click on 'List' under 'Advanced Blocks' or try to drag it into the canvas
3. Notice no effect
```

**Comment by Osho957** [comment]
@yassine-sallemi 
It appears that the API is not responding as expected, and we believe it may be due to a discrepancy in the message format
To proceed with resolving this issue, could you please provide us with the details of the expected message structure? Specifically, we need information on the values and format that the API anticipates in the message field. This will enable us to adjust our request accordingly and address the problem effectively.
