### ISSUE TITLE
🐛 [BUG] - move global types to global.d.ts file

### ISSUE THREAD

**Issue by yassinedorbozgithub** [Hexastack/Hexabot#301]
### Description

We need to move global types to the dedicated global.d.ts

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have moved the global types from various files to the global.d.ts file. This includes types from auth, user, role, model, invitation, reset, and JWT. I've also updated the global.d.ts file to include these types and removed them from their original locations.

I also created pull request: https://github.com/Hexastack/Hexabot/pull/302


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
